[platformio]
default_envs = esp32-s3-devkitc-1-v1_1

[env]
platform = espressif32@6.12.0
board = esp32-s3-devkitc-1
framework = espidf
board_build.esp-idf.sdkconfig_path = sdkconfig.local
monitor_speed = 115200
upload_speed = 230400

[env:esp32-s3-devkitc-1]
build_flags = -DPOINT_HAPTIC_LED_GPIO=48

[env:esp32-s3-devkitc-1-v1_1]
build_flags = -DPOINT_HAPTIC_LED_GPIO=38
